# Generated by Django 5.2.11 on 2026-02-17 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=255, unique=True),
                ),
                ("overview", models.TextField()),
                ("cheatsheet", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic_normalized",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple choice"),
                            ("matching_pairs", "Matching pairs"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question", models.TextField()),
                (
                    "payload",
                    models.JSONField(
                        help_text="multiple_choice: {options: [...], correct_index: int}; matching: {pairs: [{left, right}, ...]}"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "order_index"],
                "unique_together": {("course", "order_index")},
            },
        ),
    ]
