# Generated by Django 6.0.2 on 2026-02-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_add_course_generation_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="generation_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="LLM model used to generate this course (e.g. openai:gpt-5-mini). Empty for courses created before this was tracked.",
                max_length=128,
            ),
        ),
    ]
